version: "3.9"
services:
  postgres:
    image: postgres:latest
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kek
      POSTGRES_PASSWORD: kek
      POSTGRES_DB: kek