version: "3.3"
services:
  postgres:
    image: postgres:11.14-bullseye
    container_name: postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kek
      POSTGRES_PASSWORD: kek
      POSTGRES_DB: kek
  app:
    image: 'ghcr.io/moarcores/mustread/mustread:latest'
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kek
      - SPRING_DATASOURCE_USERNAME=kek
      - SPRING_DATASOURCE_PASSWORD=kek
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update