name: Build and Test Server

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build
        run: mvn -B clean package -DskipTests -f ./server/mustread/pom.xml
      - name: Test
        run: mvn -B clean verify -f ./server/mustread/pom.xml -Dspring.profiles.active=dev
